config/routes.rb
Homewrkr::Application.routes.draw do

root :to => 'home#index'

resources :assignments, :students

end

app/models/assignment.rb
# == Schema Information
#
# Table name: assignments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  group_size :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Assignment < ActiveRecord::Base
  attr_accessible :name, :group_size
  has_many :students
end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Student < ActiveRecord::Base
  attr_accessible :name
  belongs_to :assignment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
def index
end
def new
  @assignment = Assignment.new
end
def create
  assignment = Assignment.create(params[:assignment])
end
def show
    @assignment = Assignment.find(params[:id])
    @students = Student.all
    # size = @assignment.group_size
    # studentsize = @assignment.students.shuffle
    # @groupsize =  (studentsize / size)
    @studentlist = @students.pop(@assignment.group_size).join(', ')
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
def index
end
def new
  @student = Student.new
end
def create
  @student = Student.create(params[:student])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/assignments/_form.html.haml
=form_for @assignment, :url => assignments_path, :remote => true do |f|
  = f.label :name
  = f.text_field :name
  = f.label :group_size
  = f.number_field :group_size
  = f.submit 'Save'
  = link_to_function('Cancel', 'cancel_form()')

app/views/assignments/_index.html.haml
- Assignment.order(:name).each do |assignment|
  = link_to(assignment.name, assignment_path(assignment))
  = assignment.group_size

app/views/assignments/create.js.erb
$('#form').empty();
$('#results').empty();
$('#results').append('<%=j render :partial => 'index' %>');

app/views/assignments/index.html.haml
=link_to('New', new_assignment_path, :remote => true, :class => 'button')
#form
#results
  = render :partial => 'index'

app/views/assignments/new.js.erb
$('#form').empty();
$('#form').append('<%=j render :partial => 'form' %>');

app/views/assignments/show.html.haml
= @assignment.name
%br
= @assignment.students.shuffle
= @studentlist

app/views/home/index.html.haml
=link_to('Students', students_path, :class => 'button')
=link_to('Assignments', assignments_path, :class => 'button')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homewrkr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.haml
=form_for @student, :url => students_path, :remote => true do |f|
  = f.label :name
  = f.text_field :name
  = f.submit 'Save'
  = link_to_function('Cancel', 'cancel_form()')

app/views/students/_index.html.haml
- Student.order(:name).each do |student|
  = student.name

app/views/students/create.js.erb
$('#form').empty();
$('#results').empty();
$('#results').append('<%=j render :partial => 'index' %>');

app/views/students/index.html.haml
=link_to('New', new_student_path, :remote => true, :class => 'button')
#form
#results
  = render :partial => 'index'

app/views/students/new.js.erb
$('#form').empty();
$('#form').append('<%=j render :partial => 'form' %>');